### ISSUE TITLE
 Some data in the Concrete3K dataset do not match

### ISSUE THREAD

**Issue by ttkingzz** [CHDyshli/HrSegNet4CrackSegmentation#2]
Hello author, thank you for providing the project code.
But it can be seen that some images and labels do not match in the dataset downloading from Conrete3K  link, such as 359_10.jpg, 363_35.jpg, 364_28.jpg and so on. Checking the dataset again may be helpful for your model performance.

**Comment by CHDyshli** [comment]
Thank you very much for the heads up. We are checking the dataset Concrete3k and the data will be updated soon.

**Comment by CHDyshli** [comment]
Thank you very much for pointing out our mistakes. The revised dataset has been updated. In fact, in the experiment we just ran, we found that the model's results on the revised dataset far exceeded the previous ones. Many thanks again.
