### ISSUE TITLE
Poor prediction performance

### ISSUE THREAD

**Issue by 464hee** [CHDyshli/HrSegNet4CrackSegmentation#5]
![image](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/assets/100740023/fab7f3c7-5a75-4794-bcec-900810b88073)
![image](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/assets/100740023/5fc21829-1bb0-4d57-9686-2601cbb627d9)
I tried to normalize the image, but the effect seems to be the same @yongshangli @CHDyshli

**Comment by CHDyshli** [comment]
Please provide more information so I can help analyze it.

**Comment by 464hee** [comment]
Thank you for your reply, I would like to know if you are using image normalization in your training, what are the normalization parameters please.I have initially solved the problem and the split effect looks.Now I'd like to know what kind of processing you use for your images?
![1](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/assets/100740023/e65779f1-3b12-492e-bec1-5b7d5198c33f)

**Comment by 464hee** [comment]
I see in the configuration parameter file：val_dataset:
  type: Dataset
  dataset_root: data/crackseg9k
  val_path: data/crackseg9k/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize
   
With what parameters is Normalize done?

 transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
 # transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))

**Comment by CHDyshli** [comment]
```
@manager.TRANSFORMS.add_component
class Normalize:
    """
    Normalize an image.

    Args:
        mean (list, optional): The mean value of a data set. Default: [0.5,].
        std (list, optional): The standard deviation of a data set. Default: [0.5,].

    Raises:
        ValueError: When mean/std is not list or any value in std is 0.
    """

    def __init__(self, mean=(0.5, ), std=(0.5, )):
        if not (isinstance(mean, (list, tuple)) and isinstance(std, (list, tuple))) \
            and (len(mean) not in [1, 3]) and (len(std) not in [1, 3]):
            raise ValueError(
                "{}: input type is invalid. It should be list or tuple with the lenght of 1 or 3".
                format(self))
        self.mean = np.array(mean)
        self.std = np.array(std)

        from functools import reduce
        if reduce(lambda x, y: x * y, self.std) == 0:
            raise ValueError('{}: std is invalid!'.format(self))

    def __call__(self, data):
        data['img'] = functional.normalize(data['img'], self.mean, self.std)
        return data
```

**Comment by 464hee** [comment]
AttributeError: module 'functional' has no attribute 'normalize'

**Comment by 464hee** [comment]
Is functional a self written function? Can we provide it together

**Comment by 464hee** [comment]
I solved it, thanks for the reply
