### ISSUE TITLE
Dataset processing problems

### ISSUE THREAD

**Issue by Alstontk** [CHDyshli/HrSegNet4CrackSegmentation#7]
Crackseg9k How to deal with the data set, I use paddleseg to make the Images and the corresponding annotation file Mask, I switched the training image to jpg format, the training time error is as follows：
[train.txt](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/files/12999429/train.txt)
[val.txt](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/files/12999430/val.txt)

Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [2], but received [2].
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [2], but received [2].
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [2], but received [16].
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [2], but received [16].
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [2], but received [
[train.txt](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/files/12999390/train.txt)
[val.txt](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/files/12999393/val.txt)

**Comment by xiongxiong1996** [comment]
Hello, have you solved this problem? I'm also don't know how to process the data of Crackseg9k. I download Crackseg9k 3.0 at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EGIEBY.

**Comment by Alstontk** [comment]
> Hello, have you solved this problem? I'm also don't know how to process the data of Crackseg9k. I download Crackseg9k 3.0 at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EGIEBY.

still can’t solve this problem，I don't know , it feels like a difficult task

**Comment by xiongxiong1996** [comment]
yeah, CrackSeg9k 3.0 only contains 6315 images and 6752 masks, maybe we need download version 2.0?
https://github.com/Dhananjay42/crackseg9k/issues/11#issue-1958563942
In HrSegNet, they removed any unmatched image and label pairs, using only 8,751 images. It doesn't look like it's easy to find these images to use.

**Comment by yongshangli** [comment]
> yeah, CrackSeg9k 3.0 only contains 6315 images and 6752 masks, maybe we need download version 2.0? [Dhananjay42/crackseg9k#11 (comment)](https://github.com/Dhananjay42/crackseg9k/issues/11#issue-1958563942) In HrSegNet, they removed any unmatched image and label pairs, using only 8,751 images. It doesn't look like it's easy to find these images to use.

You can get the CrackSeg9k used in HrSegNet from https://chdeducn-my.sharepoint.com/:u:/g/personal/2018024008_chd_edu_cn/ETNRrhmklptIvMvVVHqtyLwBaE0yW5BlA6rUSvfnSA_u7g?e=5m5ECx.

**Comment by xiongxiong1996** [comment]
> > yeah, CrackSeg9k 3.0 only contains 6315 images and 6752 masks, maybe we need download version 2.0? [Dhananjay42/crackseg9k#11 (comment)](https://github.com/Dhananjay42/crackseg9k/issues/11#issue-1958563942) In HrSegNet, they removed any unmatched image and label pairs, using only 8,751 images. It doesn't look like it's easy to find these images to use.
> 
> You can get the CrackSeg9k used in HrSegNet from https://chdeducn-my.sharepoint.com/:u:/g/personal/2018024008_chd_edu_cn/ETNRrhmklptIvMvVVHqtyLwBaE0yW5BlA6rUSvfnSA_u7g?e=5m5ECx.

Thank you for the reply, I will continue to follow your work.

**Comment by Wangjunrui8** [comment]
May I ask how to convert the dataset to Coco format? I saw in the author's article that dividing the dataset into three labels still exists when converting to Coco format labels.
