### ISSUE TITLE
Prediction problem

### ISSUE THREAD

**Issue by patcharees** [CHDyshli/HrSegNet4CrackSegmentation#8]
Hi @yongshangli @CHDyshli 

Thanks for your great work!

I am having problem with prediction. I am using paddle=2.4.1, paddleseg=2.7.0
I tried the hrsegnetb48 and ran prediction on one image from crackseg9k (cracktree200_6227.jpg)

There is something wrong with result. Below is output from running prediction:

```
W0109 14:57:12.200444 1112407 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 10.2
W0109 14:57:12.200459 1112407 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
2024-01-09 14:57:12 [INFO]	Number of predict images = 1
2024-01-09 14:57:12 [INFO]	Loading pretrained model from /home/test/HrSegNet/hrsegnetb48/best_model/model.pdparams
2024-01-09 14:57:12 [INFO]	There are 180/180 variables loaded into HrSegNetB48.
2024-01-09 14:57:12 [INFO]	Start to predict...
1/1 [==============================] - 1s 828ms/step

```
Result in added_prediction

![cracktree200_6227](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/assets/104826856/61bef682-e0cb-450f-8450-9bc2f700757d)

Any suggestions?

**Comment by patcharees** [comment]
I found that it is my installation/library problem

**Comment by patcharees** [comment]
You can delete this issue...

**Comment by Liseria** [comment]
Hello,I am confused with the words around "registering model".Could you please tell me how to do it?

**Comment by yongshangli** [comment]
> Hello,I am confused with the words around "registering model".Could you please tell me how to do it?

![image](https://github.com/CHDyshli/HrSegNet4CrackSegmentation/assets/59642489/3cca02a4-47c6-43d2-bf40-b2e9a2e7ff54)

**Comment by Liseria** [comment]
Thank you for reply!
So it seems that this sentence is already in the "hrsegnet_b16.py".

I have configured the Paddle environment and executed the prediction according to the tutorial.
Following the tutorial, I successfully ran "sh tests/install/check_predict.sh".
Then when I ran the predict,it occurs problem.
<img width="672" alt="err1" src="https://github.com/CHDyshli/HrSegNet4CrackSegmentation/assets/53925705/4e1c40bd-fdb1-40bb-83b3-3d6c4839f87e">


python tools/predict.py --config hrseg_config/hrsegnetb16.yml  --model_path output/model.pdparams --image_path dataset/concrete3k/images --save_dir output/result

'hrseg_config' is the directory I created, which is the same level as tools.
'model.pdparams' is the best model I move from the trained model "hrsegnetb16".

WHy?

**Comment by CHDyshli** [comment]
> Thank you for reply! So it seems that this sentence is already in the "hrsegnet_b16.py".
> 
> I have configured the Paddle environment and executed the prediction according to the tutorial. Following the tutorial, I successfully ran "sh tests/install/check_predict.sh". Then when I ran the predict,it occurs problem. <img alt="err1" width="672" src="https://private-user-images.githubusercontent.com/53925705/295445022-4e1c40bd-fdb1-40bb-83b3-3d6c4839f87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTk1NzIsIm5iZiI6MTcwNDg1OTI3MiwicGF0aCI6Ii81MzkyNTcwNS8yOTU0NDUwMjItNGUxYzQwYmQtZmRiMS00MGJiLTgzYjMtM2Q2YzQ4MzlmODdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA0MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzBiMjE1ZGY4Y2JmYmQ3MjA3Nzg2ZDY2ZWY4YTBhMjkzODVkMDEwNmY3YWUxYjI4MzhlNmYyZWQ3OTI0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-0gHef20mm8uC0dnVCYQfsULpfQpCRdsGVeQxgZ2Z7c">
> 
> python tools/predict.py --config hrseg_config/hrsegnetb16.yml --model_path output/model.pdparams --image_path dataset/concrete3k/images --save_dir output/result
> 
> 'hrseg_config' is the directory I created, which is the same level as tools. 'model.pdparams' is the best model I move from the trained model "hrsegnetb16".
> 
> WHy?

Maybe you should add "from hrsegnet import *" to [this file](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/paddleseg/models/__init__.py).

**Comment by CHDyshli** [comment]
> Thank you for reply! So it seems that this sentence is already in the "hrsegnet_b16.py".
> 
> I have configured the Paddle environment and executed the prediction according to the tutorial. Following the tutorial, I successfully ran "sh tests/install/check_predict.sh". Then when I ran the predict,it occurs problem. <img alt="err1" width="672" src="https://private-user-images.githubusercontent.com/53925705/295445022-4e1c40bd-fdb1-40bb-83b3-3d6c4839f87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTk1NzIsIm5iZiI6MTcwNDg1OTI3MiwicGF0aCI6Ii81MzkyNTcwNS8yOTU0NDUwMjItNGUxYzQwYmQtZmRiMS00MGJiLTgzYjMtM2Q2YzQ4MzlmODdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA0MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzBiMjE1ZGY4Y2JmYmQ3MjA3Nzg2ZDY2ZWY4YTBhMjkzODVkMDEwNmY3YWUxYjI4MzhlNmYyZWQ3OTI0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-0gHef20mm8uC0dnVCYQfsULpfQpCRdsGVeQxgZ2Z7c">
> 
> python tools/predict.py --config hrseg_config/hrsegnetb16.yml --model_path output/model.pdparams --image_path dataset/concrete3k/images --save_dir output/result
> 
> 'hrseg_config' is the directory I created, which is the same level as tools. 'model.pdparams' is the best model I move from the trained model "hrsegnetb16".
> 
> WHy?

Also, paddleseg should be installed from source.

**Comment by Liseria** [comment]
Of course,I also installed it.

**Comment by patcharees** [comment]
Hi @CHDyshli,

I found this issue https://github.com/CHDyshli/HrSegNet4CrackSegmentation/issues/5. Is the normalization required for prediction?

Thanks in advance :-)

**Comment by CHDyshli** [comment]
> Hi @CHDyshli,
> 
> I found this issue #5. Is the normalization required for prediction?
> 
> Thanks in advance :-)

no
